### ISSUE TITLE
BSC - Extractores TC Diarios

### ISSUE THREAD

**Issue by PabloGottig** [brosenburt/PETERSEN#1]
Analizar los extractores de TC enviados por BSJ y adaptarlos a BSC

**Comment by jmusanti** [comment]
Bloqueado por restauracion de BD

**Comment by jmusanti** [comment]
Se ejecutaron los extractores y se solicito a Nicolas Zuliani que valide los datos. 

Faltan agregar nuevos campos a las tablas. Estos campos no se encuentran en las tablas mencionadas por Sistemas

**Comment by jmusanti** [comment]
Zuliani dio el OK sobre tarjetas VISA pero faltan tarjetas Master

**Comment by jmusanti** [comment]
se analizaron los casos faltantes, se detecto que algunos no estan en la credentarje y que otros no se les puede asignar la persona porque el documento no esta en la tabla sfb_bsado

**Comment by jmusanti** [comment]
Esperando pase a prod
