### ISSUE TITLE
Entes Publicos 

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/PETERSEN#2]
SISTEMAS
    - Se debe crear y correr el job de PLA mensual
    - Deben actualizar la version de SQL Server a Enterprise

PLA
    - Deben validar los reportes para los periodos disponibles

**Comment by jmusanti** [comment]
Maxi nos pide que reemplacemos el Dataflow que usa Attunity por el driver original

**Comment by PabloGottig** [comment]
Ottino reporta un error en el proceso, falta una tabla en prod

**Comment by jmusanti** [comment]
A la espera de detalle de transacciones para revisar diferencias

**Comment by jmusanti** [comment]
Se tiene que crear un reporte que provea el detalle de extracciones
