### ISSUE TITLE
BSC - Datos Cuantitativos Cliente

### ISSUE THREAD

**Issue by PabloGottig** [brosenburt/PETERSEN#27]
Buenas tardes Pablo/Joaquin,
 
Les anticipo que estamos necesitando nos puedan generar desde BI un nuevo reporte con datos cuantitativos de clientes.
Les voy pasando cuales son las necesidades para que lo vayan analizando, y luego vamos a ir enviando algunas definiciones más específicas de cada caso.
Incluye la información de Nacionalidad, Pais de Residencia y actividades económicas a considerar.
 
 
1	Total clientes (base histórica)			
2	Total clientes activos (mismo criterio que política de actualizacion legajos)
3	Total clientes activos Persona Humana (PH)			
4	Total clientes activos PH PEPs total			
5	Total clientes activos PH PEPs extranjero			
6	Total clientes activos PH residentes Argentinas		
7	Total clientes activos PH residentes Extranjero		
8	Total clientes activos PH residentes Extranjero Paises Alto Riesgo (Riesgo 4 y 5)
9	Total clientes activos PH nacionalidad Argentinas		
10	Total clientes activos PH nacionalidad Extranjera		
11	Total clientes activos PH Actividades Económicas AFIP Alto Riesgo (5)	
12	Total clientes activos Persona Jurídica (PJ)			
13	Total clientes activos PJ Sector Público			
14	Total clientes activos PJ Sector Financiero			
15	Total clientes activos PJ Sector Privado			
16	Total clientes activos PJ Actividades Económicas AFIP Alto Riesgo (5)	
17	Total clientes activos PJ Fideicomisos			
18	Total clientes activos PJ Actividades Sin fines de lucro		
19	Total clientes activos PJ Actividades Casinos y juegos de azar	
20	Total clientes activos PJ Mutuales y Cooperativas con Servicios Financieros
21	Total clientes activos PJ Consulados / Embajadas		
 
Sls,
Alfredo

**Comment by PabloGottig** [comment]
Falta responder consulta de Belèn

**Comment by PabloGottig** [comment]
Buen día Joaquín, como estas?
 
Te comento que a pedido del usuario se agregó el dato DDW.PERSONAS.PAIS_NACIMIENTO. Lo agregué en los universos Personas_R y PLAyFT.
 
¿Tienen que hacer alguna tarea adicional para que lo visualice el usuario?
 
Saludos.

**Comment by jmusanti** [comment]
![image.png](https://images.zenhubusercontent.com/5bf40416b8ceee790ed2b66b/4add06d2-a9fe-40e5-b84b-58f00dcbc57d)

Se debe finalizar el reporte que esta en test con las filas que faltan

**Comment by PabloGottig** [comment]
Buen día Tomas,

Pude acceder al Reporte y necesitaría saber de dónde proviene la información y como se generan los Totales informados. Para poder explicar en caso de que se me consulte.
Hay manera de poder obtener cuál es el detalle de los clientes Activos? Quienes son con los datos que permitan obtener el resto de los totales?

Por otra parte, me parece que estarían cruzados los datos de “Total clientes activos PF residentes Argentinos” (9 clientes) y “Total clientes activos PF residentes Extranjeros” (116.370).
No tenemos más residentes Extranjeros que Argentinos.


Gracias,

**Comment by tserra98** [comment]
Hola Tomas, los datos de nacionalidad, país y lugar de nacimiento ya fueron implementados en Producción.

El dato actividad Afip que se utiliza para identificar los casinos y juegos de azar implica un desarrollo nuevo ya que la tabla de SFB no se está incorporando a BI. Se estima comenzar la semana que viene.

Quizás pueden acordar con los usuarios un pase a Producción con lo que está probado y luego se aplica lo restante.

Saludos.
