### ISSUE TITLE
Campañas Engage - Nuevo diseño de tabla

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/PETERSEN#45]

**Comment by jmusanti** [comment]
Sistemas tiene que avanzar con el universo Engage o bien dejarnos disponibles las tablas necesarias

**Comment by PabloGottig** [comment]
Pasos a seguir:
 - corregir el modelo para que no considere la acción indicada: "BC - NO CONTACTADO"
 - modelar las tablas en el universo
 - adaptar los reportes de campañas de Agenda de Ventas al modelo de ENGAGE

**Comment by PabloGottig** [comment]
Pasar a prod el paquete y continuar modificando los reportes

**Comment by PabloGottig** [comment]
Implementar lo siguiente:
Agregar al unv un cruce con la IG para recuperar la ctdad de dias y con eso hacer un objeto tipo campaña en el unv
se debería cruzar una vez con la tabla de incentivos y con la tabla fact_altas
para que quede modelado tanto para las altas como para las campañas
ojo, q la ultima version del unv està en prod, no en dev
creo q vas a necesitar poner dos veces la ig con distintos alias
esto es para no modificar el proceso
y porq ademàs te va a faltar el dato en la tabla de incentivos

**Comment by PabloGottig** [comment]
Finalizar los 3 reportes que quedan pendientes. Ver definiciones para el reporte creado por David.

**Comment by PabloGottig** [comment]
Buenas tardes.

Estuvimos analizando el reporte. Le hicimos unas correcciones menores (ejemplo cambiar agenda de ventas por engage, o arreglar las variables del encabezado)..

En cuanto a los datos, veo que no coinciden en tres productos con lo que se informa en el tablero general de campañas:
