### ISSUE TITLE
BSC - Movimientos TC

### ISSUE THREAD

**Issue by PabloGottig** [brosenburt/PETERSEN#47]
Se envio a nico datos de enero para su validacion

**Comment by PabloGottig** [comment]
Tomas: buenas tardes, estuve revisando los movimientos de visa y encontré que en BI hay más o menos unas 1000 operaciones que no están apareciendo, te adjunto un Excel con alguno ejemplos para que puedas ver porque no están,
 
No pude identificar algún patrón entre los casos.
 
Avísame cualquier cosa.

**Comment by tserra98** [comment]
Tomas: buenas tardes, se corrigió la relación entre las tablas. Con relación a los movimientos estarían faltando solo 227 de 99544, no sé por qué motivo, te los adjunto en un Excel.
 
Cualquier cosa avísame.
 
Saludos.

**Comment by PabloGottig** [comment]
Tomas: buenas tardes, estoy controlando los movimientos de MasterCard en producción y que en BI están faltando unos 10000 movimientos, podrás revisarlo por favor.

Te adjunto los movimientos faltantes y el sql de la consulta.

**Comment by jmusanti** [comment]
Buenas tardes Tomas, 

previo al UPDATE el registro en dw_procesos para tp_Fact_Mov_Visa estaba en estado = 0, es decir que en el paquete no incluye la modificación del estado una vez que finaliza la ejecución o el paquete tiene un error:

 

Ejecuté el UPDATE y luego los paquetes manualmente:

 

 

Una vez finalizadas las tareas, los registros en dw_procesos quedaron así:

 

Por favor analizar y corregir lo que corresponda.
