### ISSUE TITLE
BSC - Agregar campo IGR Prom

### ISSUE THREAD

**Issue by jmusanti** [brosenburt/PETERSEN#49]
Se debe agregar el campo IGR Prom a la alerta

**Comment by PabloGottig** [comment]
Falta pasar a Producción

**Comment by jmusanti** [comment]
Esperando pase a prod

**Comment by jmusanti** [comment]
Buen día Joaquín, como estas?

Nos reporta Andrea lo siguiente:

![image.png](https://images.zenhubusercontent.com/5bf40416b8ceee790ed2b66b/f94a4584-d770-42b2-b9cc-768b390263b8)
